nodeLinker: node-modules

plugins:
  - checksum: e183406dae0b56ce2dcf0880f6b4f8dd4bd1a50ebc8e06f37f05c375dae351476019a3c324443c1b9fa5ed0b3ad2053fae39810d66c16d84c4fc0365f531e650
    path: .yarn/plugins/yarn-plugin-nixify.cjs
    spec: "https://raw.githubusercontent.com/stephank/yarn-plugin-nixify/main/dist/yarn-plugin-nixify.js"
